//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pull_PeachTree
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento_Detalle
    {
        public int ID { get; set; }
        public int numeroAsiento { get; set; }
        public string codigoCuenta { get; set; }
        public string nombreCuenta { get; set; }
        public string tipoCuenta { get; set; }
        public Nullable<decimal> valorCuenta { get; set; }
        public string detalleCuenta { get; set; }
    
        public virtual Asiento Asiento { get; set; }
    }
}
